
services:
  test-db:
    image: postgres:15-alpine
    container_name: inventory_test_db
    environment:
      POSTGRES_DB: test_inventory
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5434:5432"  # Puerto diferente para no conflictuar
    volumes:
      # BD en memoria RAM para velocidad
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_inventory"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  test-api:
    build: .
    container_name: inventory_test_api
    environment:
      FLASK_ENV: testing
      PYTHONPATH: /app
      SQLALCHEMY_DATABASE_URI: postgresql://test_user:test_password@test-db:5432/test_inventory
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./htmlcov:/app/htmlcov
    networks:
      - test-network
    depends_on:
      test-db:
        condition: service_healthy
    command: bash -c "cd /app && tail -f /dev/null"        #flask run --host=0.0.0.0 --port=8000

networks:
  test-network:
    driver: bridge
