
services:
  web:
    build: .
    container_name: inventario_api
    env_file: .env
    environment:
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USE_TLS=True
      - MAIL_USE_SSL=False
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: inventario_db
    env_file: .env
    ports:
      - "5433:5432"   # mapeo del puerto 5433 del host â†’ 5432 del contenedor.
    volumes:
      - inventario_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  inventario_data:
